### ISSUE TITLE
整体进度

### ISSUE THREAD

**Issue by wizardforcel** [apachecn/ds-cmd-line-2e-zh#1]
| 章节 | 字数 | 贡献者 | 进度 | 奖励 |
| --- | --- | --- | --- | --- |
| [序](https://github.com/apachecn/ds-cmd-line-2e-zh/blob/master/docs/i.md) | 1224 |  @Ting-xin | 完成  | √ |
| [前言](https://github.com/apachecn/ds-cmd-line-2e-zh/blob/master/docs/ii.md) | 4056 | @Ting-xin | 完成 | √ |
| [1 简介](https://github.com/apachecn/ds-cmd-line-2e-zh/blob/master/docs/01.md) | 4819 | @Ting-xin | 完成 | √ |
| [2 开始](https://github.com/apachecn/ds-cmd-line-2e-zh/blob/master/docs/02.md) | 7230 | @Ting-xin | 完成 | √ |
| [3 获取数据](https://github.com/apachecn/ds-cmd-line-2e-zh/blob/master/docs/03.md) | 5415 | @Ting-xin | 完成 | √ |
| [4 创建命令行工具](https://github.com/apachecn/ds-cmd-line-2e-zh/blob/master/docs/04.md) | 6271 | @Alex19830624 |完成  | √ |
| [5 清理数据](https://github.com/apachecn/ds-cmd-line-2e-zh/blob/master/docs/05.md) | 7931 | @Alex19830624 |完成  | √ |
| [6 项目管理与`make`](https://github.com/apachecn/ds-cmd-line-2e-zh/blob/master/docs/06.md) | 4198 | @Alex19830624 |完成  | √ |
| [7 探索数据](https://github.com/apachecn/ds-cmd-line-2e-zh/blob/master/docs/07.md) | 7124 | @Alex19830624 |完成  | √ |
| [8 并行管道](https://github.com/apachecn/ds-cmd-line-2e-zh/blob/master/docs/08.md) | 6833 | @Alex19830624 |完成  | √ |
| [9 建模数据](https://github.com/apachecn/ds-cmd-line-2e-zh/blob/master/docs/09.md) | 4975 | @Alex19830624 |完成  | √ |
| [10 多语言数据科学](https://github.com/apachecn/ds-cmd-line-2e-zh/blob/master/docs/10.md) | 2987 | @Alex19830624 |完成  | √ |
| [11 总结](https://github.com/apachecn/ds-cmd-line-2e-zh/blob/master/docs/11.md) | 2455 | @Alex19830624 |完成  | √ |
| [附录：命令行工具列表](https://github.com/apachecn/ds-cmd-line-2e-zh/blob/master/docs/12.md) | 4271 | @Alex19830624 |完成  | √ |

**Comment by NewRudy** [comment]
大佬好，想参与一下相关的工作：章节 序+前言+1+2+3+7: 1344591831

**Comment by wizardforcel** [comment]
@Ting-xin 认领成功，开始你的表演~

**Comment by NewRudy** [comment]
大佬，我把剩下的也校对了吧，但可能会比较慢

**Comment by wizardforcel** [comment]
> 大佬，我把剩下的也校对了吧，但可能会比较慢

OK

**Comment by Alex19830624** [comment]
飞龙大佬，那我把剩下的都认领了吧。阿姨
